apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: a0my9vboz-python 
  janus-idp.io/tekton: a0my9vboz-python
  backstage.io/kubernetes-id: a0my9vboz-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: a0my9vboz-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  